------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Fragment Shaders 
-- 
sAmbientOcclusionFragment_frag = [[  
// glslf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslf -po version=330
// source file: sAmbientOcclusionFragment.fcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslf
//program main
//semantic samplerGBuffer0
//semantic samplerAO
//var float4 oColor : $vout.COLOR : COLOR : 0 : 1

precision mediump float;

vec4 _oColor1;

 // main procedure, the original name was main
void main()
{


    _oColor1 = vec4( 0.00000000E+000, 0.00000000E+000, 0.00000000E+000, 0.00000000E+000);
    gl_FragColor = vec4( 0.00000000E+000, 0.00000000E+000, 0.00000000E+000, 0.00000000E+000);
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
