------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Fragment Shaders 
-- 
sParticleRenderFragment_frag = [[  
// glslf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslf -po version=330
// source file: sParticleRenderFragment.fcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslf
//program main
//semantic main.AgeScale
//semantic main.samplerColor
//semantic main.samplerPTex
//var float AgeScale :  : _AgeScale1 : 8 : 1
//var sampler1D samplerColor :  : _samplerColor1 : 9 : 1
//var sampler2D samplerPTex :  : _samplerPTex1 : 10 : 1
//var float2 tex : $vin.TEXCOORD0 : TEXCOORD0 : 0 : 1
//var float1 age : $vin.TEXCOORD1 : TEXCOORD1 : 1 : 1
//var float4 iColor : $vin.COLOR :  : 2 : 0
//var float4 Pos : $vin.WPOS :  : 3 : 0
//var float4 oColor0 : $vout.COLOR0 : COLOR0 : 4 : 1
//var float4 oColor1 : $vout.COLOR1 : COLOR1 : 5 : 1
//var float4 oColor2 : $vout.COLOR2 : COLOR2 : 6 : 1
//var float4 oColor3 : $vout.COLOR3 : COLOR3 : 7 : 1

precision mediump float;

vec4 _oColor01;
vec4 _oColor21;
vec4 _oColor11;
vec4 _oColor31;
float _age1;
uniform float _AgeScale1;
uniform sampler2D _samplerColor1;
uniform sampler2D _samplerPTex1;
float _c0004;
varying vec4 cg_TexCoord1;
varying vec4 cg_TexCoord0;

 // main procedure, the original name was main
void main()
{

    vec4 _pc;
    vec4 _t;

    _age1 = cg_TexCoord1.x;
    _c0004 = _age1*_AgeScale1;
    _pc = texture2D(_samplerColor1, vec2(_c0004, 0.0));
    _t = texture2D(_samplerPTex1, cg_TexCoord0.xy);
    _oColor01 = _t*_pc;

    float rem = mod(gl_FragCoord.x, 3.0);
    if(rem < 1.0) {
        gl_FragColor = _oColor01;
    }
    else {
        if(rem < 2.0) {
            gl_FragColor = _oColor21;
        }
        else {
            gl_FragColor = _oColor11;
        }
    }
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
