------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Fragment Shaders 
-- 
sResolveFragment_frag = [[  
// glslf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslf -po version=330
// source file: sResolveFragment.fcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslf
//program main
//semantic main.samplerGBuffer3
//semantic main.samplerLBuffer0
//semantic main.samplerLBuffer1
//semantic main.BloomScale
//semantic main.samplerBloom0
//semantic main.samplerBloom1
//semantic main.samplerBloom2
//semantic main.samplerBloom3
//semantic main.samplerPost
//semantic main.samplerToneMap
//semantic main.samplerShadow
//semantic main.samplerCollision
//semantic main.samplerAmbient
//semantic main.texelScale
//var sampler2D samplerLBuffer0 :  : _samplerLBuffer01 : 4 : 1
//var sampler2D samplerLBuffer1 :  : _samplerLBuffer11 : 5 : 1
//var float BloomScale :  : _BloomScale1 : 6 : 1
//var sampler2D samplerBloom0 :  : _samplerBloom01 : 7 : 1
//var sampler2D samplerBloom1 :  : _samplerBloom11 : 8 : 1
//var sampler2D samplerBloom2 :  : _samplerBloom21 : 9 : 1
//var sampler2D samplerBloom3 :  : _samplerBloom31 : 10 : 1
//var sampler2D samplerPost :  : _samplerPost1 : 11 : 1
//var sampler2D samplerToneMap :  : _samplerToneMap1 : 12 : 1
//var float2 texelScale :  : _texelScale1 : 16 : 1
//var float2 tex : $vin.TEXCOORD0 : TEXCOORD0 : 0 : 1
//var float4 iColor : $vin.COLOR :  : 1 : 0
//var float4 oColor : $vout.COLOR : COLOR : 2 : 1

precision mediump float;

vec4 _oColor1;
vec4 _TMP3;
vec4 _TMP2;
vec4 _TMP1;
uniform sampler2D _samplerLBuffer01;
uniform sampler2D _samplerLBuffer11;
uniform float _BloomScale1;
uniform sampler2D _samplerBloom01;
uniform sampler2D _samplerBloom11;
uniform sampler2D _samplerBloom21;
uniform sampler2D _samplerBloom31;
uniform sampler2D _samplerPost1;
uniform sampler2D _samplerToneMap1;
uniform vec2 _texelScale1;
vec2 _c0023;
vec2 _c0025;
vec2 _c0027;
vec2 _c0029;
vec2 _c0043;
vec2 _c0045;
vec2 _c0047;
varying vec4 cg_TexCoord0;

 // main procedure, the original name was main
void main()
{

    vec4 _LBuf0;
    vec4 _LBuf1_0;
    vec4 _LBuf1_1;
    vec4 _LBuf1_2;
    vec4 _LBuf1_3;
    vec4 _LBuf1_4;
    vec4 _LBuf1;
    vec4 _Bloom0;
    vec4 _Bloom1;
    vec4 _Bloom2;
    vec4 _Bloom3;
    vec4 _Post;
    vec3 _Spec;
    vec3 _Color;

    _LBuf0 = texture2D(_samplerLBuffer01, cg_TexCoord0.xy);
    _LBuf1_0 = texture2D(_samplerLBuffer11, cg_TexCoord0.xy);
    _c0023 = cg_TexCoord0.xy + vec2(_texelScale1.x, 0.00000000E+000);
    _LBuf1_1 = texture2D(_samplerLBuffer11, _c0023);
    _c0025 = cg_TexCoord0.xy + vec2(0.00000000E+000, _texelScale1.y);
    _LBuf1_2 = texture2D(_samplerLBuffer11, _c0025);
    _c0027 = cg_TexCoord0.xy + vec2(-_texelScale1.x, 0.00000000E+000);
    _LBuf1_3 = texture2D(_samplerLBuffer11, _c0027);
    _c0029 = cg_TexCoord0.xy + vec2(0.00000000E+000, -_texelScale1.y);
    _LBuf1_4 = texture2D(_samplerLBuffer11, _c0029);
    _LBuf1 = (_LBuf1_0*3.00000000E+000 + _LBuf1_1 + _LBuf1_2 + _LBuf1_3 + _LBuf1_4)*1.42857149E-001;
    _Bloom0 = texture2D(_samplerBloom01, cg_TexCoord0.xy);
    _Bloom1 = texture2D(_samplerBloom11, cg_TexCoord0.xy);
    _Bloom2 = texture2D(_samplerBloom21, cg_TexCoord0.xy);
    _Bloom3 = texture2D(_samplerBloom31, cg_TexCoord0.xy);
    _Post = texture2D(_samplerPost1, cg_TexCoord0.xy);
    _Spec = _LBuf1.xyz + _BloomScale1*(_Bloom0*5.00000000E-001 + 2.50000000E-001*_Bloom1 + 1.25000000E-001*_Bloom2 + 1.25000000E-001*_Bloom3).xyz + _Post.xyz*_Post.w;
    _Color = _LBuf0.xyz + _Spec;
    _c0043 = vec2(_Color.x, 0.00000000E+000);
    _TMP1 = texture2D(_samplerToneMap1, _c0043);
    _c0045 = vec2(_Color.y, 2.50000000E-001);
    _TMP2 = texture2D(_samplerToneMap1, _c0045);
    _c0047 = vec2(_Color.z, 5.00000000E-001);
    _TMP3 = texture2D(_samplerToneMap1, _c0047);
    _oColor1 = vec4(_TMP1.x, _TMP2.x, _TMP3.x, 0.00000000E+000);
    gl_FragColor = _oColor1;
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
