------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Fragment Shaders 
-- 
sShadowMergeFragment_frag = [[  
// glslf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslf -po version=330
// source file: sShadowMergeFragment.fcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslf
//program main
//semantic main.samplerLBuffer0
//semantic main.samplerLBuffer1
//semantic main.BloomScale
//semantic main.samplerBloom0
//semantic main.samplerBloom1
//semantic main.samplerBloom2
//semantic main.samplerBloom3
//semantic main.samplerToneMap
//semantic main.samplerShadow
//var sampler2D samplerShadow :  : _samplerShadow1 : 11 : 1
//var float2 tex : $vin.TEXCOORD0 : TEXCOORD0 : 0 : 1
//var float4 iColor : $vin.COLOR :  : 1 : 0
//var float4 oColor : $vout.COLOR : COLOR : 2 : 1

#version 330

vec4 _oColor1;
float _TMP3;
uniform sampler2DShadow _samplerShadow1;
vec3 _coord0033;
vec3 _c0033;
in vec4 cg_TexCoord0;
out vec4 cg_FragColor;

 // main procedure, the original name was main
void main()
{


    _c0033 = vec3(cg_TexCoord0.x, cg_TexCoord0.y, 6.00000024E-001);
    _coord0033.xy = _c0033.xy;
    _coord0033.z = _c0033.z;
    _TMP3 = texture(_samplerShadow1, _coord0033);
    _oColor1 = vec4(_TMP3, _TMP3, _TMP3, _TMP3);
    cg_FragColor = vec4(_TMP3, _TMP3, _TMP3, _TMP3);
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
