------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Fragment Shaders 
-- 
sShadowFragment_frag = [[  
// glslf output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslf -po version=330
// source file: sShadowFragment.fcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslf
//program main
//var float4 Pos : $vin.WPOS : WPOS : 0 : 1
//var float4 oColor0 : $vout.COLOR : COLOR : 1 : 1
//var float oDepth : $vout.DEPTH : DEPR : 2 : 1

precision mediump float;

vec4 _oColor01;
float _oDepth1;

 // main procedure, the original name was main
void main()
{
    _oColor01 = vec4( 1.0, 1.0, 1.0, 1.0);
//    _oDepth1 = gl_FragCoord.z;
    gl_FragColor = vec4( 1.0, 1.0, 1.0, 1.0);
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
