------------------------------------------------------------------------------------------------------------  
-- 
-- Autogenerated lua Vertex Shaders 
-- 
sVoxelVertex_vert = [[  
// glslv output by Cg compiler
// cgc version 3.1.0013, build date Apr 18 2012
// command line args: -quiet -profile glslv -po version=330
// source file: sVoxelVertex.vcg
//vendor NVIDIA Corporation
//version 3.1.0.13
//profile glslv
//program main
//semantic main.modelViewProj
//var float4x4 modelViewProj :  : _modelViewProj1[0], 4 : 4 : 1
//var float3 position : $vin.POSITION : POSITION : 0 : 1
//var float4 color : $vin.COLOR : COLOR : 1 : 1
//var float2 tex : $vin.TEXCOORD0 : TEXCOORD0 : 2 : 1
//var float3 N : $vin.TEXCOORD1 : TEXCOORD1 : 3 : 1
//var float4 main.position : $vout.POSITION : HPOS : -1 : 1
//var float4 main.color : $vout.COLOR : COLOR : -1 : 1
//var float2 main.tex : $vout.TEXCOORD0 : TEXCOORD0 : -1 : 1
//var float3 main.N : $vout.TEXCOORD1 : TEXCOORD1 : -1 : 1

#version 330

struct Output {
    vec4 _position2;
    vec4 _color1;
    vec2 _tex1;
    vec3 _N1;
};

uniform vec4 _modelViewProj1[4];
vec4 _r0003;
vec4 _v0003;
in vec4 COLOR;
in vec4 TEXCOORD0;
in vec4 TEXCOORD1;
in vec4 cg_Vertex;
out vec4 cg_FrontColor;
out vec4 cg_TexCoord1;
out vec4 cg_TexCoord0;

 // main procedure, the original name was main
void main()
{


    _v0003 = vec4(cg_Vertex.x, cg_Vertex.y, cg_Vertex.z, 1.00000000E+000);
    _r0003.x = dot(_modelViewProj1[0], _v0003);
    _r0003.y = dot(_modelViewProj1[1], _v0003);
    _r0003.z = dot(_modelViewProj1[2], _v0003);
    _r0003.w = dot(_modelViewProj1[3], _v0003);
    cg_TexCoord0.xy = TEXCOORD0.xy;
    cg_TexCoord1.xyz = TEXCOORD1.xyz;
    gl_Position = _r0003;
    cg_FrontColor = COLOR;
    return;
} // main end
]] 
-- 
------------------------------------------------------------------------------------------------------------  
