@echo OFF
REM Append all files to a list to include once!
echo ------------------------------------------------------------------------------------------------------------  > fmadShaders.lua
echo -- Autogenerated fmad Shaders >> fmadShaders.lua
echo -- >> fmadShaders.lua

set fmadpath=byt3d/fmad/shaders/

REM Convert Vert Shaders
for %%f in (*.vcg) do (

    echo ------------------------------------------------------------------------------------------------------------  > %%~nf.lua
    echo -- >> %%~nf.lua
    echo -- Autogenerated lua Vertex Shaders >> %%~nf.lua
    echo -- >> %%~nf.lua
    echo %%~nf_vert = [[  >> %%~nf.lua
    cgc -quiet -profile glslv -po version=330 %%f >> %%~nf.lua
    echo ]] >> %%~nf.lua
    echo -- >> %%~nf.lua
    echo ------------------------------------------------------------------------------------------------------------  >> %%~nf.lua

    echo require("%fmadpath%%%~nf"^) >> fmadShaders.lua
)
    
REM Convert Frag Shaders    
for %%f in (*.fcg) do (

    echo ------------------------------------------------------------------------------------------------------------  > %%~nf.lua
    echo -- >> %%~nf.lua
    echo -- Autogenerated lua Fragment Shaders >> %%~nf.lua
    echo -- >> %%~nf.lua
    echo %%~nf_vert = [[  >> %%~nf.lua
    cgc -quiet -profile glslf -po version=330 %%f >> %%~nf.lua
    echo ]] >> %%~nf.lua
    echo -- >> %%~nf.lua
    echo ------------------------------------------------------------------------------------------------------------  >> %%~nf.lua

    echo require("%fmadpath%%%~nf"^) >> fmadShaders.lua
)
    
echo -- >> fmadShaders.lua
echo ------------------------------------------------------------------------------------------------------------  >> fmadShaders.lua
    